version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: todo-app-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: todoist
      POSTGRES_PASSWORD: aIU0Ys5hrBPho647FLBpzl+Q37IM5mQhTgUhTqt25mE=
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U todoist -d todoist"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: todo-app-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --save 60 1 --loglevel warning
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  redis_data: 